import { Component, OnInit } from '@angular/core';
import { EsquemasService } from '../../services/esquemas.service';
import { Camada } from 'app/models/camadas';

@Component({
  selector: 'simulador-vendas',
  templateUrl: './simulador-vendas.component.html',
  styleUrls: ['./simulador-vendas.component.scss'],
})
export class SimuladorVendasComponent implements OnInit {

  public camadafullData: any;
  public camadaType:any;

  constructor( ) { }

  ngOnInit() {
    this.camadafullData  =[
      {camada:{cod_camada:"CA007",nome_camada:"PRECO_BASE",tipo_base_vendas:"V",value:""},condicaos:[{cod_condicao:"CO006",sequencias:[{cod_sequencia:"SQ001",campos:[],nome_sequencia:"CODESTUNI/CODCNL"}],desco_condicao:"PRECO_BASE",escala_qtde:0,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA007",cod_chavecontas:"CC002",cod_tipovalor:"TV001",idCondicaoCamadaEsquema:"EC000CO006CA007"}],condicaosAllow:[{cod_condicao:"CO006",sequencias:[{cod_sequencia:"SQ001",campos:[],nome_sequencia:"CODESTUNI/CODCNL"}],desco_condicao:"PRECO_BASE",escala_qtde:0,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA007",cod_chavecontas:"CC002",cod_tipovalor:"TV001",idCondicaoCamadaEsquema:"EC000CO006CA007"}],tipoValor:[{cod_tipovalor:"TV000",desc_tipovalor:"PERCENTUAL"},{cod_tipovalor:"TV001",desc_tipovalor:"VALOR"},{cod_tipovalor:"TV002",desc_tipovalor:"CALCULADO"}]},
      {camada:{cod_camada:"CA008",nome_camada:"MARGEM",tipo_base_vendas:"V",value:""},condicaos:[{cod_condicao:"CO000",sequencias:[{cod_sequencia:"SQ000",campos:[{cod_campo:"CP000",nome_campo:"CODTERCHV"},{cod_campo:"CP001",nome_campo:"CODCNL"}],nome_sequencia:"CODTERCHV/CODCNL"}],desco_condicao:"MARGEM_CANAL",escala_qtde:0,"pos_neg":"P",tip_base_vendas:"V",mandatoria:0,"estatistica":1,cod_camada:"CA008",cod_chavecontas:"CC001",cod_tipovalor:"TV001",idCondicaoCamadaEsquema:"EC001CO000CA001"}],condicaosAllow:[{cod_condicao:"CO000",sequencias:[{cod_sequencia:"SQ000",campos:[{cod_campo:"CP000",nome_campo:"CODTERCHV"},{cod_campo:"CP001",nome_campo:"CODCNL"}],nome_sequencia:"CODTERCHV/CODCNL"}],desco_condicao:"MARGEM_CANAL",escala_qtde:0,"pos_neg":"P",tip_base_vendas:"V",mandatoria:0,"estatistica":1,cod_camada:"CA008",cod_chavecontas:"CC001",cod_tipovalor:"TV001",idCondicaoCamadaEsquema:"EC001CO000CA001"}],tipoValor:[{cod_tipovalor:"TV000",desc_tipovalor:"PERCENTUAL"},{cod_tipovalor:"TV001",desc_tipovalor:"VALOR"},{cod_tipovalor:"TV002",desc_tipovalor:"CALCULADO"}]},
      {camada:{cod_camada:"CA009",nome_camada:"OPERACIONAL",tipo_base_vendas:"V",value:""},condicaos:[{cod_condicao:"CO007",sequencias:[{cod_sequencia:"SQ002",campos:[],nome_sequencia:"CODESTUNI/FLETE"}],desco_condicao:"FLETE",escala_qtde:0,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA009",cod_chavecontas:"CC000",cod_tipovalor:"TV001",idCondicaoCamadaEsquema:"EC000CO007CA009"},{cod_condicao:"CO010",sequencias:[{cod_sequencia:"SQ005",campos:[],nome_sequencia:"VNCDORIGEM/VNDESTINOCLI/VNTIPODECLIENTE"},{cod_sequencia:"SQ006",campos:[],nome_sequencia:"VNQUATIDADECLI/VNCODPGTO"},{cod_sequencia:"SQ004",campos:[],nome_sequencia:"VNCDORIGEM/VNDESTINOCLI"}],desco_condicao:"FRETE2",escala_qtde:1,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA009",cod_chavecontas:null,cod_tipovalor:"TV000",idCondicaoCamadaEsquema:"EC000CO010CA009"}],condicaosAllow:[{cod_condicao:"CO007",sequencias:[{cod_sequencia:"SQ002",campos:[],nome_sequencia:"CODESTUNI/FLETE"}],desco_condicao:"FLETE",escala_qtde:0,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA009",cod_chavecontas:"CC000",cod_tipovalor:"TV001",idCondicaoCamadaEsquema:"EC000CO007CA009"},{cod_condicao:"CO010",sequencias:[{cod_sequencia:"SQ005",campos:[],nome_sequencia:"VNCDORIGEM/VNDESTINOCLI/VNTIPODECLIENTE"},{cod_sequencia:"SQ006",campos:[],nome_sequencia:"VNQUATIDADECLI/VNCODPGTO"},{cod_sequencia:"SQ004",campos:[],nome_sequencia:"VNCDORIGEM/VNDESTINOCLI"}],desco_condicao:"FRETE2",escala_qtde:1,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA009",cod_chavecontas:null,cod_tipovalor:"TV000",idCondicaoCamadaEsquema:"EC000CO010CA009"}],tipoValor:[{cod_tipovalor:"TV000",desc_tipovalor:"PERCENTUAL"},{cod_tipovalor:"TV001",desc_tipovalor:"VALOR"},{cod_tipovalor:"TV002",desc_tipovalor:"CALCULADO"}]},
      {camada:{cod_camada:"CA010",nome_camada:"FINANCEIRO",tipo_base_vendas:"V",value:""},condicaos:[{cod_condicao:"CO005",sequencias:[{cod_sequencia:"SQ000",campos:[{cod_campo:"CP000",nome_campo:"CODTERCHV"},{cod_campo:"CP001",nome_campo:"CODCNL"}],nome_sequencia:"CODTERCHV/CODCNL"}],desco_condicao:"TEST_CHAVECONTAS",escala_qtde:1,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":1,cod_camada:"CA010",cod_chavecontas:null,cod_tipovalor:"TV001",idCondicaoCamadaEsquema:"EC000CO005CA010"},{cod_condicao:"CO008",sequencias:[{cod_sequencia:"SQ003",campos:[],nome_sequencia:"CODCNL/IVA"}],desco_condicao:"IVA",escala_qtde:0,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA010",cod_chavecontas:"CC001",cod_tipovalor:"TV000",idCondicaoCamadaEsquema:"EC000CO008CA010"},{cod_condicao:"CO009",sequencias:[{cod_sequencia:"SQ000",campos:[{cod_campo:"CP000",nome_campo:"CODTERCHV"},{cod_campo:"CP001",nome_campo:"CODCNL"}],nome_sequencia:"CODTERCHV/CODCNL"},{cod_sequencia:"SQ001",campos:[],nome_sequencia:"CODESTUNI/CODCNL"}],desco_condicao:"NOVA_CONDICAO",escala_qtde:1,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA010",cod_chavecontas:"CC001",cod_tipovalor:"TV000",idCondicaoCamadaEsquema:"EC000CO009CA010"}],condicaosAllow:[{cod_condicao:"CO005",sequencias:[{cod_sequencia:"SQ000",campos:[{cod_campo:"CP000",nome_campo:"CODTERCHV"},{cod_campo:"CP001",nome_campo:"CODCNL"}],nome_sequencia:"CODTERCHV/CODCNL"}],desco_condicao:"TEST_CHAVECONTAS",escala_qtde:1,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":1,cod_camada:"CA010",cod_chavecontas:null,cod_tipovalor:"TV001",idCondicaoCamadaEsquema:"EC000CO005CA010"},{cod_condicao:"CO008",sequencias:[{cod_sequencia:"SQ003",campos:[],nome_sequencia:"CODCNL/IVA"}],desco_condicao:"IVA",escala_qtde:0,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA010",cod_chavecontas:"CC001",cod_tipovalor:"TV000",idCondicaoCamadaEsquema:"EC000CO008CA010"},{cod_condicao:"CO009",sequencias:[{cod_sequencia:"SQ000",campos:[{cod_campo:"CP000",nome_campo:"CODTERCHV"},{cod_campo:"CP001",nome_campo:"CODCNL"}],nome_sequencia:"CODTERCHV/CODCNL"},{cod_sequencia:"SQ001",campos:[],nome_sequencia:"CODESTUNI/CODCNL"}],desco_condicao:"NOVA_CONDICAO",escala_qtde:1,"pos_neg":"0",tip_base_vendas:"V",mandatoria:0,"estatistica":0,cod_camada:"CA010",cod_chavecontas:"CC001",cod_tipovalor:"TV000",idCondicaoCamadaEsquema:"EC000CO009CA010"}],tipoValor:[{cod_tipovalor:"TV000",desc_tipovalor:"PERCENTUAL"},{cod_tipovalor:"TV001",desc_tipovalor:"VALOR"},{"cod_tipovalor":"TV002",desc_tipovalor:"CALCULADO"}]}
    ];
    // this.updateMasterData();
  }



}
